http:
  routers:
    noc-report-app:
      rule: "Host(`0.0.0.0`) && PathPrefix(`/noc-report`)"
      service: "noc-report-app"
      entryPoints:
        - web

  services:
    noc-report-app:
      loadBalancer:
        servers:
          - url: "http://noc-report-downtime-app:3002"
